FORMAT: 1A


# MajesticThai

Majestic Thai is a high-tech Thai restuarant with its own API. 

## Dishes Collection [/dishes]

### List Dishes [GET]

+ Response 200 (application/json)

        [
           {
           "_id":"1",
           "name":"Drunk Beef",
           "price":11.5,
           "description":"sauteed beef and basil with Thai chilis in a spicy sauce"
           }, {
           "_id":"2",
           "name":"Phad Phrik Pow",
           "price":11,
           "description":"stir-fried meat in coconut milk cooked in smoked chili sauce"
           }, {
           "_id":"3",
           "name":"Panang Curry",
           "price":12,
           "description":"panang curry cooked in coconut milk with bamboo shoots"
           }, {
           "_id":"4",
           "name":"Chicken Satay",
           "price":5,
           "description":"our tender, seasoned chicken on pork skewers"
           }
        ]
        
## Dish [/dishes/{id}]

+ Parameters 
    + id (number) - ID of the dish in the form of an integer

### List Dish [GET]

+ Response 200 (application/json)

        {
        "_id":"1",
        "name":"Drunk Beef",
        "price":11.5,
        "description":"sauteed beef and basil with Thai chilis in a spicy sauce"
        }

## Order Collection [/orders]

### List Orders [GET]

+ Response 200 (application/json)

        [
        {
        "order_id": "1",
        "username": "elbaumpj",
        "time": "12:30",
        "total": 22.5,
        "items": [
            {
           "_id":"1",
           "name":"Drunk Beef",
           "price":11.5,
           "description":"sauteed beef and basil with Thai chilis in a spicy sauce"
           }, {
           "_id":"2",
           "name":"Phad Phrik Pow",
           "price":11,
           "description":"stir-fried meat in coconut milk cooked in smoked chili sauce"
           }
         ]
        },
        {
        "order_id": "2",
        "username": "elbaumpj",
        "time": "15:30",
        "total": 17,
        "items": [
            {
           "_id":"3",
           "name":"Panang Curry",
           "price":12,
           "description":"panang curry cooked in coconut milk with bamboo shoots"
           }, {
           "_id":"4",
           "name":"Chicken Satay",
           "price":5,
           "description":"our tender, seasoned chicken on pork skewers"
           }
         ]
        }
        ]
      
## Order [/orders/{id}]

+ Parameters 
    + id (number) - ID of the order in the form of an integer

### List Order [GET]

+ Response 200 (application/json)
    
        {
        "order_id": "1",
        "username": "elbaumpj",
        "time": "12:30",
        "total": 22.5,
        "items": [
            {
           "_id":"1",
           "name":"Drunk Beef",
           "price":11.5,
           "description":"sauteed beef and basil with Thai chilis in a spicy sauce"
           }, {
           "_id":"2",
           "name":"Phad Phrik Pow",
           "price":11,
           "description":"stir-fried meat in coconut milk cooked in smoked chili sauce"
           }
        ]
        }